name: Server Tests

on:
  pull_request:
    paths:
      - "server/**"
      - "proto/**"
      - "router/**"
      - "launcher/**"

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          override: true
          components: rustfmt, clippy
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Loading cache.
        uses: actions/cache@v2
        id: model_cache
        with:
          path: ~/.cache/huggingface/
          key: models
      - name: Install
        run: |
          make install
      - name: Run server tests
        run: |
          pip install pytest
          pytest -sv server/tests
      - name: Run Rust tests
        run: |
          cargo test
